pool:
  vmImage: ubuntu-16.04

steps:

- task: Docker@2
  displayName: Push Image to Docker Hub
  inputs:
    containerRegistry: dockerHub
    repository: poulad/uniwards-web-api
    command: buildAndPush
    tags: |
      latest
      $(Build.BuildId)

- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: heroku
    repository: uniwards-api/web
    command: push
    tags: |
      latest
