pool:
  vmImage: ubuntu-16.04

steps:

- task: Docker@2
  displayName: Build & Push Image to Heroku
  inputs:
    containerRegistry: heroku
    repository: uniwards-api/web
    command: buildAndPush
    tags: |
      latest
      $(Build.BuildId)

- bash: curl -X POST --fail --show-error -H 'Content-Length: 0' -u '$uniwards-api:wupqLKPop7dAv3i4HLSd2nECeJvLf0H4FxPDxZ8foundKyQxQNhkMjQwvRof' 'https://uniwards-api.scm.azurewebsites.net/docker/hook'
