pool:
  vmImage: ubuntu-16.04

steps:

- task: Docker@2
  displayName: Build & Push Image to Heroku
  inputs:
    containerRegistry: heroku
    repository: uniwards-api/web
    command: buildAndPush
    tags: latest
