pool:
  vmImage: ubuntu-16.04

variables:
  imageName: uniwards-web-api

steps:
- task: Docker@2
  displayName: Build Docker Image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: Dockerfile

- task: Docker@2
  displayName: Push Image to Docker Hub
  inputs:
    containerRegistry: dockerHub
    repository: $(imageName)
    command: push
    tags: |
      latest
      $(Build.BuildId)
